# Generated by Django 3.1 on 2020-08-24 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('products', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Price_Bybrand',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.product')),
                ('Starbucks', models.IntegerField(null=True)),
                ('Twosome', models.IntegerField(null=True)),
                ('TomandToms', models.IntegerField(null=True)),
                ('Ediya', models.IntegerField(null=True)),
                ('Mega', models.IntegerField(null=True)),
                ('Hollys', models.IntegerField(null=True)),
                ('Coffeebean', models.IntegerField(null=True)),
                ('Coffeebay', models.IntegerField(null=True)),
                ('Angelinus', models.IntegerField(null=True)),
                ('Pascucci', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Bybrand',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.product')),
                ('Starbucks', models.CharField(max_length=30, null=True)),
                ('Twosome', models.CharField(max_length=30, null=True)),
                ('TomandToms', models.CharField(max_length=30, null=True)),
                ('Ediya', models.CharField(max_length=30, null=True)),
                ('Mega', models.CharField(max_length=30, null=True)),
                ('Hollys', models.CharField(max_length=30, null=True)),
                ('Coffeebean', models.CharField(max_length=30, null=True)),
                ('Coffeebay', models.CharField(max_length=30, null=True)),
                ('Angelinus', models.CharField(max_length=30, null=True)),
                ('Pascucci', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
